### ISSUE TITLE
Z Homing is incorrectly set in Config.g

### ISSUE THREAD

**Issue by dmyers7** [chrishamm/configtool#12]
Only using a home switch for my Z axis.  The output config.g file incorrectly references the Z axis homing method in each of the call outs (z home Active low / disabled, Active High, Probe, current stall detection) so that the one I want gets stomped on by each of the configurations that follow incorrectly.  Manually editing the config.g and removing the Z1 reference from each of the follow on homing options corrects the problem and prevents my bed from crashing into the print heads.

**Comment by chrishamm** [comment]
Thanks for your report, I just fixed it in version 2.0.2.
