### ISSUE TITLE
No deployprobe.g and retractprobe.g created

### ISSUE THREAD

**Issue by b0ssman** [chrishamm/configtool#13]
Selecting BLTouch will not cause deployprobe.g and retractprobe.g to be generated

**Comment by chrishamm** [comment]
Thanks, I'll fix it.

**Comment by Spudaddict** [comment]
Having a similar error, also using a BLTouch:
"Failed to create deployprobe.g: Error: Could not find matching close tag for "<%".

**Comment by Dud3z** [comment]
Same here. im not very good at gcode. can somebody please give some example files? i want to configure my bltouch.

**Comment by chrishamm** [comment]
Can you try again? It should be fixed now.

**Comment by b0ssman** [comment]
files are generated now.

**Comment by b0ssman** [comment]
although the Servo Control Channel: combobox does not work anymore.

**Comment by chrishamm** [comment]
Thanks for the note, that should be fixed in 2.1.1 too.
