### ISSUE TITLE
Incorrect Homing Scripts for CoreXY and Delta

### ISSUE THREAD

**Issue by b0ssman** [chrishamm/configtool#18]
The config generates H2 G1 movements for delta and corexy.

this is incorrect as H2 only moves one motor.

e.g
Homedelta 
G1 H2 Z-5 F6000           ; move down a few mm so that the nozzle can be centred
This will move only the z motor on a delta.

CoreXY
homex 
G1 H2 X-5 F6000  ; go back a few mm
this wil move x and y on a corexy machine

i would sugget to only use H2 on a cartesian machine

**Comment by chrishamm** [comment]
Thanks, this should be fixed in v2.1.4.
