### ISSUE TITLE
PT100 assignments on RRF Tool

### ISSUE THREAD

**Issue by gadget808** [chrishamm/configtool#20]
I am building out my Ender 5+ (w/Chimera+) with a Duet3 board.  When I attempt to config the PT100 Sensors it only give me the option for spi.cs1 -spi.cs4.  I would only get 2000 degrees on my 1st sensor.  I manually changed the config.g to spi.cs0 for 1st pt100 and spi.cs1 for the second pt100  now both sensors register temp.
So the RRF Config Tool needs to start with spi.cs0  not spi.cs1.

Aloha
Mike

**Comment by chrishamm** [comment]
Yes, that's right. Thanks for the report!

**Comment by chrishamm** [comment]
It's fixed in v2.1.5.
