### ISSUE TITLE
Defaults for Duet 2 WiFi, RRF 3, and Ender 3 have some issues.

### ISSUE THREAD

**Issue by JoshWobbles** [chrishamm/configtool#22]
Issue 1 is the default Z drive endstop pin is set to (not assigned) in the tool, this should be zstop.
Issue 2 Unknown config issue is causing a bed heater fault.

Attaching the config generated using the default settings (except for fixing issue 1 which was obvious to me) in hopes that someone can also tell me what is wrong with the bed heater settings.
[config (1).zip](https://github.com/chrishamm/configtool/files/4023534/config.1.zip)

**Comment by chrishamm** [comment]
Thanks for the report. There was an issue in the configtool that sometimes replaced values with `null` (like the Z endstop pin) but it's fixed in v2.1.5. I've updated the Ender 3 Pro template again.
