### ISSUE TITLE
Closing quotation mark not present on password value in config.g

### ISSUE THREAD

**Issue by jpatrick-09** [chrishamm/configtool#4]
Not sure if this actually affects how the machine reads the password value, but I noticed in the config.g files I generated there is a colon at the end of the password instead of a closing quotation mark. 

I found the issue in the source code on line 23 of the config.ejs file. Just a little thing, but I saw it, and thought I would let you know. 

![capture](https://user-images.githubusercontent.com/33104188/52860292-a0d55600-30f4-11e9-9be2-cbda8d584e34.PNG)

**Comment by chrishamm** [comment]
Thanks, will fix
