### ISSUE TITLE
Add common thermistors

### ISSUE THREAD

**Issue by b0ssman** [chrishamm/configtool#5]
an we include the most common Marlin Thermistors Tables in the Reprap Configurator?
https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x/Marlin/src/module/thermistor

i.e.
Thermistor 1 - EPCOS 100k - // R25 = 100 kOhm, beta25 = 4092 K, 4.7 kOhm pull-up, bed thermistor
Thermistor 5 - ATC Semitec 104GT-2 Already there
Thermistor 11 - 100k beta 3950 1% thermistor (4.7k pullup) // R25 = 100 kOhm, beta25 = 3950 K, 4.7 kOhm pull-up, QU-BD silicone bed QWG-104F-3950 thermistor
Thermistor 13 - 100k Hisens 3950 1% up to 300°C for hotend "Simple ONE " & "Hotend "All In ONE" // R25 = 100 kOhm, beta25 = 4100 K, 4.7 kOhm pull-up, Hisens thermistor

**Comment by chrishamm** [comment]
Thanks for this suggestion, I've added all of them to the config tool.
