### ISSUE TITLE
Don't deploy BLTouch in bed.g

### ISSUE THREAD

**Issue by matthewmorrison** [chrishamm/configtool#6]
Having M98 Pdeployprobe.g in bed.g causes the BLTouch to slam into the side of the bed at start because it deploys at home, which on mine and I'm sure at least some other printers is z < 0. G29 already deploys the probe when it gets in position so this isn't necessary. 

If removing this causes problems for other configurations a checkbox at least would be helpful since this issue causes damage to the BLTouch.

Duet 2 Wifi fw1.21

**Comment by chrishamm** [comment]
Thanks for this report, it's fixed in the latest version. I changed it to generate deployprobe.g/retractprobe.g, but these macros are no longer invoked by the homing/bed macro files. I hope that is OK.
