### ISSUE TITLE
New firmware 2.03 with updates on GCODE

### ISSUE THREAD

**Issue by pipersw** [chrishamm/configtool#7]
The new firmware 2.03 is out, and some changes on GCODE are introduced : [https://github.com/dc42/RepRapFirmware/blob/dev/WHATS_NEW.md](url) 

The configurator need to be updated, if possible.

**Comment by chrishamm** [comment]
I have just published a new configtool version which brings several enhancements. I read the "whats new" article but I do not see any problem. Are there any incompatibilities in the latest configtool version? If so, please open an issues for every problem you find.
