### ISSUE TITLE
Some bugs with latest update

### ISSUE THREAD

**Issue by kinta70** [chrishamm/configtool#8]
Hi Guys,
I've just been playing with the new tool & found some problems that you may not be aware of.

1. Network information is split between to & bottom of config page causing config loading problems.
2. The Automatic power saving settings are also at the top of the page (no biggie) however after moving it down the bottom I found that I was still having trouble with Laser Filament Monitor setting that came after it. Once changing the single quote mark back to a quote all was good.

Keep up the great work.
Cheers,

**Comment by chrishamm** [comment]
Thanks, both issues are fixed in v2.0.2.
